name: Security checks

on:
  pull_request:

jobs:
  check:
    name: Check for crypto
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for crypto
        uses: defi-wonderland/check-crypto-action@v1
        with:
          title: Check private key and notify
          branch: main
          notify_check: true
          token: ${{ secrets.GITHUB_TOKEN }}